#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <iostream>
#include <sstream>
#include <string>
#include <vector>

static std::string makeIdentifier(const std::string& path, size_t index) {
    std::string ident = "asset_" + std::to_string(index) + "_";
    for (char c : path) {
        if (std::isalnum(static_cast<unsigned char>(c))) {
            ident += c;
        } else {
            ident += '_';
        }
    }
    return ident;
}

int main(int argc, char** argv) {
    if (argc < 2) {
        std::cerr << "Usage: bin2c <output.cpp> <asset1> [asset2 ...]\n";
        return 1;
    }

    const std::string outputPath = argv[1];
    std::vector<std::string> assetPaths;
    for (int i = 2; i < argc; ++i) {
        assetPaths.push_back(argv[i]);
    }

    std::ostringstream out;
    out << "// Auto-generated by tools/bin2c.cpp. Do not edit by hand.\n";
    out << "#include \"core/assets.h\"\n";
    out << "#include <unordered_map>\n";
    out << "#include <string>\n\n";

    std::vector<std::string> identifiers;
    std::vector<size_t> sizes;

    for (size_t i = 0; i < assetPaths.size(); ++i) {
        const std::string& path = assetPaths[i];

        std::ifstream file(path, std::ios::binary);
        if (!file) {
            std::cerr << "bin2c: could not open asset file: " << path << "\n";
            return 1;
        }

        std::vector<unsigned char> bytes(
            (std::istreambuf_iterator<char>(file)),
            std::istreambuf_iterator<char>());

        const std::string ident = makeIdentifier(path, i);
        identifiers.push_back(ident);
        sizes.push_back(bytes.size());

        out << "static const unsigned char " << ident << "[] = {";
        for (size_t j = 0; j < bytes.size(); ++j) {
            if (j % 20 == 0)
                out << "\n    ";
            out << static_cast<unsigned int>(bytes[j]) << ",";
        }
        if (bytes.empty()) {
            // Zero-length arrays aren't valid C++; pad with a dummy byte.
            out << "0";
        }
        out << "\n};\n\n";
    }

    out << "static const std::unordered_map<std::string, AssetData>& getAssetMap() {\n";
    out << "    static const std::unordered_map<std::string, AssetData> table = {\n";
    for (size_t i = 0; i < assetPaths.size(); ++i) {
        out << "        { \"" << assetPaths[i] << "\", { "
            << identifiers[i] << ", " << sizes[i] << "u } },\n";
    }
    out << "    };\n";
    out << "    return table;\n";
    out << "}\n\n";

    out << "const AssetData* getEmbeddedAsset(const std::string& path) {\n";
    out << "    const auto& table = getAssetMap();\n";
    out << "    auto it = table.find(path);\n";
    out << "    if (it == table.end()) return nullptr;\n";
    out << "    return &it->second;\n";
    out << "}\n";

    std::ofstream outFile(outputPath, std::ios::binary);
    if (!outFile) {
        std::cerr << "bin2c: could not open output file for writing: " << outputPath << "\n";
        return 1;
    }
    outFile << out.str();

    std::cout << "bin2c: embedded " << assetPaths.size() << " assets into "
              << outputPath << "\n";
    return 0;
}